[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_plugin3"
version = "1.0"
description = "description of project1"

[project.entry-points."stevedore_testplugins.database"]
my_plugin3 = "plugin3:myfunc2"