[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_plugin2"
version = "1.0"
description = "description of project1"

[project.entry-points."stevedore_testplugins.database"]
my_plugin2 = "plugin2:myfunc2"